name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
      - uses: samuelmeuli/action-snapcraft@fceeb3c308e76f3487e72ef608618de625fb7fe8 #v3.0.1
      - run: sudo snap install openscad-nightly
      - run: make setup
      - run: openscad-nightly --enable lazy-union -o /tmp/CI.3mf *.scad # TODO: `--backend Manifold` is not available. This makes the build *much, much, much* slower.
